apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjZXBnYmFzZWFjci5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiZTlhNGNjZWQtY2JjOC00MmYwLWFjZjktMDZlNjUzOTZhZDk5IiwicGFzc3dvcmQiOiJzSm44UX5+WW16OW9UT3ZZSEVkVTU2WEY3TUtOZ3VNc3JvMEhTY3VtIiwiYXV0aCI6IlpUbGhOR05qWldRdFkySmpPQzAwTW1Zd0xXRmpaamt0TURabE5qVXpPVFpoWkRrNU9uTktiamhSZm41WmJYbzViMVJQZGxsSVJXUlZOVFpZUmpkTlMwNW5kVTF6Y204d1NGTmpkVzA9In19fQ==
kind: Secret
metadata:
  name: acr-auth
  namespace: "82107479"
type: kubernetes.io/dockerconfigjson
